import tailwindcssAnimate from "tailwindcss-animate";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        surface: "hsl(var(--background))",
        "surface-dim": "hsl(var(--background))",
        "surface-bright": "#2c2c2c",
        "surface-variant": "#262626",
        "surface-container-lowest": "#000000",
        "surface-container-low": "hsl(var(--muted))",
        "surface-container": "hsl(var(--card))",
        "surface-container-high": "#20201f",
        "surface-container-highest": "#262626",
        "surface-tint": "hsl(var(--primary))",
        "primary-dim": "#7e51ff",
        "primary-container": "#a98fff",
        "primary-fixed": "#a98fff",
        "primary-fixed-dim": "#9c7eff",
        "on-primary": "hsl(var(--primary-foreground))",
        "on-primary-container": "#280072",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#32008a",
        "secondary-dim": "#00d4ec",
        "secondary-container": "#006875",
        "secondary-fixed": "#26e6ff",
        "secondary-fixed-dim": "#00d7f0",
        "on-secondary": "#004d57",
        "on-secondary-container": "#e8fbff",
        "on-secondary-fixed": "#003a42",
        "on-secondary-fixed-variant": "#005964",
        tertiary: "#ff96bb",
        "tertiary-dim": "#ee77a3",
        "tertiary-container": "#fb81ae",
        "tertiary-fixed": "#ff8db6",
        "tertiary-fixed-dim": "#f57ca9",
        "on-tertiary": "#690939",
        "on-tertiary-container": "#59002e",
        "on-tertiary-fixed": "#37001a",
        "on-tertiary-fixed-variant": "#70103e",
        error: "hsl(var(--destructive))",
        "error-dim": "#d73357",
        "error-container": "#a70138",
        "on-error": "#490013",
        "on-error-container": "#ffb2b9",
        outline: "#767575",
        "outline-variant": "hsl(var(--border))",
        "on-background": "hsl(var(--foreground))",
        "on-surface": "hsl(var(--foreground))",
        "on-surface-variant": "hsl(var(--muted-foreground))",
        "inverse-surface": "#fcf9f8",
        "inverse-on-surface": "#565555",
        "inverse-primary": "#6834eb",
      },
      fontFamily: {
        headline: ["Manrope", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "0.75rem",
      },
      minHeight: {
        "editor-workspace": "calc(100dvh - 7rem)",
        "dialogue-panel-min": "12rem",
      },
      maxHeight: {
        "editor-scroll": "calc(100dvh - 7rem)",
        "dialogue-panel": "min(50vh, 28rem)",
        "editor-preview": "min(70vh, 42rem)",
        "editor-preview-sm": "min(35vh, 21rem)",
      },
      width: {
        "editor-sidebar": "26rem",
      },
      boxShadow: {
        primaryGlow: "0 0 24px rgba(182, 160, 255, 0.12)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [tailwindcssAnimate],
};
