/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#0e0e0e",
        surface: "#0e0e0e",
        "surface-dim": "#0e0e0e",
        "surface-bright": "#2c2c2c",
        "surface-variant": "#262626",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#131313",
        "surface-container": "#1a1a1a",
        "surface-container-high": "#20201f",
        "surface-container-highest": "#262626",
        "surface-tint": "#b6a0ff",
        primary: "#b6a0ff",
        "primary-dim": "#7e51ff",
        "primary-container": "#a98fff",
        "primary-fixed": "#a98fff",
        "primary-fixed-dim": "#9c7eff",
        "on-primary": "#340090",
        "on-primary-container": "#280072",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#32008a",
        secondary: "#00e3fd",
        "secondary-dim": "#00d4ec",
        "secondary-container": "#006875",
        "secondary-fixed": "#26e6ff",
        "secondary-fixed-dim": "#00d7f0",
        "on-secondary": "#004d57",
        "on-secondary-container": "#e8fbff",
        "on-secondary-fixed": "#003a42",
        "on-secondary-fixed-variant": "#005964",
        tertiary: "#ff96bb",
        "tertiary-dim": "#ee77a3",
        "tertiary-container": "#fb81ae",
        "tertiary-fixed": "#ff8db6",
        "tertiary-fixed-dim": "#f57ca9",
        "on-tertiary": "#690939",
        "on-tertiary-container": "#59002e",
        "on-tertiary-fixed": "#37001a",
        "on-tertiary-fixed-variant": "#70103e",
        error: "#ff6e84",
        "error-dim": "#d73357",
        "error-container": "#a70138",
        "on-error": "#490013",
        "on-error-container": "#ffb2b9",
        outline: "#767575",
        "outline-variant": "#484847",
        "on-background": "#ffffff",
        "on-surface": "#ffffff",
        "on-surface-variant": "#adaaaa",
        "inverse-surface": "#fcf9f8",
        "inverse-on-surface": "#565555",
        "inverse-primary": "#6834eb",
      },
      fontFamily: {
        headline: ["Manrope", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
      minHeight: {
        "editor-workspace": "calc(100dvh - 7rem)",
        "dialogue-panel-min": "12rem",
      },
      maxHeight: {
        "editor-scroll": "calc(100dvh - 7rem)",
        "dialogue-panel": "min(50vh, 28rem)",
        "editor-preview": "min(70vh, 42rem)",
        "editor-preview-sm": "min(35vh, 21rem)",
      },
      width: {
        "editor-sidebar": "26rem",
      },
      boxShadow: {
        primaryGlow: "0 0 24px rgba(182, 160, 255, 0.12)",
      },
    },
  },
  plugins: [],
};
