"""Postgres access — SQLAlchemy ORM."""
from backend.db.repository import (
    Generation,
    User,
    UserBackground,
    create_user,
    delete_user_background,
    get_generation_by_job_uid,
    get_user_background,
    get_user_by_id,
    init_db,
    insert_generation,
    insert_user_background_record,
    list_generations_for_user,
    list_user_backgrounds,
    set_user_gallery_public,
    verify_user,
)

__all__ = [
    "User",
    "UserBackground",
    "Generation",
    "init_db",
    "create_user",
    "verify_user",
    "get_user_by_id",
    "set_user_gallery_public",
    "insert_user_background_record",
    "list_user_backgrounds",
    "get_user_background",
    "delete_user_background",
    "insert_generation",
    "get_generation_by_job_uid",
    "list_generations_for_user",
]
